steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/gcloud-demo-452713/my-cloud-run-service/my-image:${SHORT_SHA}', '.']

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/gcloud-demo-452713/my-cloud-run-service/my-image:${SHORT_SHA}']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'my-cloud-run-service'
    - '--image'
    - 'us-central1-docker.pkg.dev/gcloud-demo-452713/my-cloud-run-service/my-image:${SHORT_SHA}'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
images:
  - 'us-central1-docker.pkg.dev/gcloud-demo-452713/my-cloud-run-service/my-image:${SHORT_SHA}'
